# Generated by Django 3.0.2 on 2020-01-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
