# Generated by Django 3.0.2 on 2020-01-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_post_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(max_length=255, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='post',
            name='original_id',
            field=models.CharField(max_length=255, verbose_name='id на сайте источника'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parse_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название поста'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст тега'),
        ),
    ]
